version: 2.1
executors:
  test-executor:
    resource_class: xlarge
    machine:
      image: ubuntu-2004:202010-01

jobs:
  echo-tag:
    executor: test-executor
    description: Format Check
    steps:
      - checkout
      - run:
          name: Echo Envs
          command: |
            echo $CIRCLE_TAG
  echo-when-tag:
    executor: test-executor
    steps:
      - run:
          name: Echo when tagged
          command: |
            echo $CIRCLE_TAG
            echo ${CIRCLE_TAG/''/v}
workflows:
  test:
    jobs:
      - echo-tag
      - echo-when-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
            

      
